import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const ClientWrapper = dynamic(() => import("@/components/ClientWrapper"), {
  ssr: false,
});
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ttalkak",
  description: "Generated by Ttalkak",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className="h-full">
      <body className={`${inter.className} flex flex-col min-h-full`}>
        <ClientWrapper>
          <header>
            <NavBar />
          </header>
          <main className="flex-grow container justify-center items-center px-10 py-10">
            {children}
          </main>
          <Footer />
        </ClientWrapper>
      </body>
    </html>
  );
}
